### ISSUE TITLE
How Filecoin Works (Nicola's) - Organize & Summary

### ISSUE THREAD

**Issue by walkerlj0** [protocol/launchpad#114]
## Problem Description
Currently the major set of information that is in 'The Filecoin Protocol' page: [https://protocol-labs.gitbook.io/launchpad-curriculum](https://protocol-labs.gitbook.io/launchpad-curriculum) is in a Google Drive folder, which is too lengthy to reasonably consumed by people in the launchpad program.

We need to split this video up into 4 videos, in manageable sections (chapters identified by time, given a title) for someone to consume in a shorter amount of time.

### Purpose

**Describe the solution you'd like**
 Ideally there would be 4 videos split up into sections (chapters) with a summary of the main point/ concepts written in a ~1-2 page document, which can then be [uploaded into this section of the curriculum](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/filecoin/sealing-proving#how-the-filecoin-protocol-works)

**Where Can we find out more about this topic?**
All content is in this drive:
https://drive.google.com/drive/folders/1stQQlqN-V7tBwfSAcyLKnhCuViCTbwWm

This will replace the content in the curriculum here: https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/filecoin/sealing-proving#how-the-filecoin-protocol-works

**Additional context**
To get access to these materials, including the Google drive where rough resources are located, the Gdrive where you should upload edited videos, and the Sheet where you record summaries & chapters for resources, as well as assets that you can use for title slides in the video editing
contact Lindsay Walker/ walkerlj0

## Milestones
**1) Separate & Section Videos** 
Create 4 separate videos, each with different chapters (give a relevant title), referred to by time, and with titles (lower third or title page) edited into the video. These videos should be edited down to make it easier to process/ learn the relevant content in ~1-2 hours of time. 

Write Video Summary & chapters in the [Filecoin Tab here](https://docs.google.com/spreadsheets/d/1uyN_5uL4y6EFQVV7UHpPtiMQ_WWx9nzC36MCtNyCPfY/edit?usp=sharing)

Videos should be uploaded here: (https://drive.google.com/drive/folders/1ZTb6ggyVmwmxsZDTi8wKJ2HslavOsxJ0?usp=sharing)

**2) Written Summary** Write a 1-2 page summary of important concepts, separated by headers that are named the same as the chapters (sections) that the video is broken up into. Add any relevant links for deeper reading, submitted in a .md file as a PR to protocol/launchpad or as a Google Doc

**3) Review Process** Allow for up to 3 revision cycles where specific asks about video editing & edits to written summary are made

## Acceptance Criteria
_Describe the output and criteria for this output for considering this task completed_
There are 4 videos that are total, less than 1.5 hours in length, that include all relevant data from Nicola's talk about How the Filecoin Protocol Works, with title slides ([example](https://www.youtube.com/watch?v=A9Lo_rLNU9w)) for each section, each section identified by name in the Launchpad YouTube spreadsheet, with a 1-2 page summary([example](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/ipfs/how-ipfs-works#how-ipfs-works)) (Google Doc or Notion) of the key concepts in each section

**Comment by Annamarie2019** [comment]
@walkerlj0 There are a lot of links on this page. I can't figure out which of the many links are "this video" that you want split up into 4. I see a page with six videos on it, but I don't see a name for any of them. So is that it, just the one video to be split up and described? Let me know which video and I'll get right to it.

**Comment by walkerlj0** [comment]
@Annamarie2019 There are several videos, under the section that says:

All content is in this drive:
https://drive.google.com/drive/folders/1stQQlqN-V7tBwfSAcyLKnhCuViCTbwWm

I would like you to take those three, shorten them, and break them up into 3-4 videos (however the content makes sense to you)

**Comment by Annamarie2019** [comment]
Aha! Thanks, @walkerlj0

**Comment by Annamarie2019** [comment]
7/10/22: Made progress paring a 32-minute video down to 16 minutes, but have a question in to @walkerlj0 about spacing between audio vs visual track.

**Comment by Annamarie2019** [comment]
I've uploaded the edited file to: https://drive.google.com/drive/folders/1ZTb6ggyVmwmxsZDTi8wKJ2HslavOsxJ0

**Comment by walkerlj0** [comment]
Part 1 of 3 (or 4) Has been completed and is uploaded to YouTube. See Details in the 'Filecoin' tab in column 10 : https://docs.google.com/spreadsheets/d/1uyN_5uL4y6EFQVV7UHpPtiMQ_WWx9nzC36MCtNyCPfY/edit#gid=1764198807

**Comment by walkerlj0** [comment]
Did part 1, too large of scope to do entire set
