### ISSUE TITLE
Hands on Videos for Filecoin on Testnet

### ISSUE THREAD

**Issue by walkerlj0** [protocol/launchpad#122]
**Is your feature request related to a problem with the curriculum? Please describe.**
Users need to get their 'hands on' to start to understand how Filecoin works for miners and storage providers. Create a set of 4-5 videos showing users how to set up a testnet on their machine, 

**Describe the solution you'd like**
There should be 5-6 videos on roughly the following topics
1) Make & Build a Lotus Node
2) Initializing a node on testnet (with Jenn's instructions for a .zshrc & .toml files)
3) Start a Devnet & explore
4) Create a wallet & explore
5) How Storage works - make devnet, sectors, then devinit'
6) Exploring with your miner & making a deal

\\

Follow the style of this here: https://www.youtube.com/watch?v=9pUqOhORsYI

**Where Can we find out more about this topic?**
See Recording Here for a flow: https://drive.google.com/file/d/1TDMR_XXHUqxvvmoQq4JAeKAfDsRZ0Xiw/view?usp=sharing
See this Notion page for Notes: https://www.youtube.com/watch?v=9pUqOhORsYI
See Jenn's Notion page for setup: https://www.notion.so/pl-strflt/Test-in-lotus-local-devnet-08618dac5bb54d00837c6dabf08913b8

**How can you contribute and help create this content?**

**Additional context**
jennijuju is a good resources for this

**Comment by mishmosh** [comment]
This WIP tutorial might be a good content outline to follow: https://github.com/filecoin-project/filecoin-docs/pull/1190

**Comment by walkerlj0** [comment]
NA, too much change, will use tutorials on Filecion/ lotus site during colo
