### ISSUE TITLE
libp2p Content Improvements

### ISSUE THREAD

**Issue by walkerlj0** [protocol/launchpad#124]
**Is your feature request related to a problem with the curriculum? Please describe.**
Currently the libp2p content isn't well written, and some sections simply contain one video with no written content.

**Describe the solution you'd like**
Add the specific improvements to the following pages:

**[libp2p Intro](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/libp2p#tutorials)** add a diagram of the 'pieces' or layers

**[libp2p Connections and Users](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/libp2p/libp2p-connections-users)** Add a summary of the videos with key points written down. Do research on this topic area and add better content. Also add in [assessment questions](https://docs.google.com/document/d/1cpVT7EkcWzKe0Vb1ENk_jeSY1tB6RhVzy0fmXZbvao0/edit) to go along with this

**[Decentralized Messaging](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/libp2p/decentralized-messaging)** Add a summary of the videos with key points written down. Do research on this topic area and add better content. Also add in [assessment questions](https://docs.google.com/document/d/1cpVT7EkcWzKe0Vb1ENk_jeSY1tB6RhVzy0fmXZbvao0/edit) to go along with this

**[Distributed Networking Solutions](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/libp2p/distributed-networking-solutions)** Add a summary of the videos with key points written down. Do research on this topic area and add better content. Also add in [assessment questions](https://docs.google.com/document/d/1cpVT7EkcWzKe0Vb1ENk_jeSY1tB6RhVzy0fmXZbvao0/edit) to go along with this

**[NAT Traversal and Hole Punching](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/libp2p/nat-traversal-hole-punching)** add a diagram or some kind of explainer video

**Where Can we find out more about this topic?**

**How can you contribute and help create this content?**

**Additional context**

**Comment by walkerlj0** [comment]
@Enol
This is the approach I'm taking for the libp2p section:
* [Core Concepts](http://%28https//protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/libp2p/core-concepts) no changes, just adding a diagram
* [Libp2p Connections](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/libp2p/libp2p-connections-users)
removing the [first video](https://www.youtube.com/watch?v=zcWHamr5m_k), and replacing it with [this video](https://www.youtube.com/watch?v=bWY0op7FmJ8&), which basically covers the same content but in a better way
I'm also adding text to support the videos.
We should also add a small tutorial on how to set up a libp2p node
* [Decentralized Messaging](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/libp2p/decentralized-messaging): the video is 1h 30 min showing how to create a chat application with libp2p. I think cadets should try more basic stuff before getting to this, so I'd remove it for now or place it at the end of the libp2p section as super optional
* [Gossipsub](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/libp2p/gossipsub): no major changes
* [Distributed Networking Solutions](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/libp2p/distributed-networking-solutions):
The first video is moved to the Libp2p connections section
Add content about using the DHT in libp2p
The second video covers again the chat app, which I think it's too advanved to the previous samples that we have. We can keep it and summarize it though.

**Comment by enolal826** [comment]
Connections & Users section: https://github.com/protocol/launchpad/pull/154
DHT: https://github.com/protocol/launchpad/pull/163
Circuit Relays & PubSub: https://github.com/protocol/launchpad/pull/167

**Comment by walkerlj0** [comment]
@mrodriguez3313 review #164 && 167 then we can move to done once @enolal826 merges

**Comment by enol** [comment]
you guys are talking to the wrong enol haha. I don’t know anything about
this repository, must’ve been a confusion.

**Comment by walkerlj0** [comment]
Done/ duplicate
