### ISSUE TITLE
How IPFS Deals with Files - Organize & Summarize

### ISSUE THREAD

**Issue by walkerlj0** [protocol/launchpad#130]
## Problem Description
Currently the major set of information that is in 'IPLD & IPFS' section of the curriculum: [https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/ipld/ipld-and-ipfs](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/ipld/ipld-and-ipfs) is too lengthy to reasonably consumed by people in the launchpad program.

We need to pare down this video into one 30 minute video, in manageable sections (chapters identified by time, given a title) for someone to consume in a shorter amount of time.

### Purpose

**Describe the solution you'd like**
 Ideally there would be a ~ 30 min video split into sections (chapters) with a summary of the main point/ concepts written in a ~2 paragraph document, which can then be [uploaded into this section of the curriculum](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/filecoin/sealing-proving#how-the-filecoin-protocol-works)

This video will replace the one here: https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/ipld/ipld-and-ipfs

Write Video Summary & chapters in the [IPLD Tab here](https://docs.google.com/spreadsheets/d/1uyN_5uL4y6EFQVV7UHpPtiMQ_WWx9nzC36MCtNyCPfY/edit?usp=sharing)
Videos should be uploaded here: [(https://drive.google.com/drive/folders/1iGoaA8u-wUKcy2H5m7yRUmfxQ0xrm8Cf?usp=sharing](https://drive.google.com/drive/folders/1iGoaA8u-wUKcy2H5m7yRUmfxQ0xrm8Cf?usp=sharing))

**Where Can we find out more about this topic?**
You will have to use software to download & edit the video from here: https://www.youtube.com/watch?v=Y_-TWTmF_1I&t=2s

This will replace some of the content in the curriculum here: https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/ipld/ipld-and-ipfs

**Additional context**
To get access to these materials, including the Google drive where rough resources are located, the Gdrive where you should upload edited videos, and the Sheet where you record summaries & chapters for resources, as well as assets that you can use for title slides in the video editing
contact Lindsay Walker/ walkerlj0

## Milestones
**1) Separate & Section Videos** 
Create a 30 min video with different chapters (give a relevant title), referred to by time, and with titles (lower third or title page) edited into the video. These videos should be edited down to make it easier to process/ learn the relevant content. 

Write Video Summary & chapters in the [IPLD Tab here](https://docs.google.com/spreadsheets/d/1uyN_5uL4y6EFQVV7UHpPtiMQ_WWx9nzC36MCtNyCPfY/edit?usp=sharing)

Videos should be uploaded here: (https://drive.google.com/drive/folders/13-Xqs5lXsDGhiPnspR-dopubBl3X6Gr-)

**2) Written Summary** Write a ~2 paragraph summary of important concepts, separated by headers that are named the same as the chapters (sections) that the video is broken up into. Add any relevant links for deeper reading, submitted in a .md file as a PR to protocol/launchpad or as a Google Doc, for this page: https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/ipld/ipld-and-ipfs

**3) Review Process** Allow for up to 3 revision cycles where specific asks about video editing & edits to written summary are made

## Acceptance Criteria
_Describe the output and criteria for this output for considering this task completed_
There is a video less than 30 minutes in length, that includes all relevant info from the IPFS Camp talk, with title slides ([example](https://www.youtube.com/watch?v=A9Lo_rLNU9w)) for each section, each section identified by name in the Launchpad YouTube spreadsheet, with a 1-2 page summary([example](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/ipfs/how-ipfs-works#how-ipfs-works)) (Google Doc or Notion) of the key concepts in each section

**Comment by walkerlj0** [comment]
@mrodriguez3313 I downloaded the video from YouTube and put it here: https://drive.google.com/file/d/129M0a3wKnjcvgW_jrjUQySbJrYlgfOeB/view?usp=sharing

**Comment by walkerlj0** [comment]
@mrodriguez3313 once you finish the video, could you also create 1 assessment question, put it here: https://docs.google.com/document/d/1cpVT7EkcWzKe0Vb1ENk_jeSY1tB6RhVzy0fmXZbvao0/edit?usp=sharing

Once it is written tag/ assign me in a comment in the GDoc with +lindsay.walker@protocol.ai

**Comment by mrodriguez3313** [comment]
Okay 👍 (for GH tracking) I have a rough version of the video uploaded here https://drive.google.com/drive/folders/1NXXwYLaFWF-QQRzP_HLddho9SR7xDGM- its the one prefixed with v1.

I added a question and tagged you in the assessment

**Comment by walkerlj0** [comment]
TBD @walkerlj0 review videos as of now. @mrodriguez3313 add in title slides

**Comment by walkerlj0** [comment]
@mrodriguez3313 can you add the link to the summary paragraphs here?

**Comment by walkerlj0** [comment]
Summary paragraph: https://docs.google.com/document/d/1FIWa01sdhvrjPMF8FvP-XPhCD1lscId4bYCEI_q3Bwg/edit

**Comment by walkerlj0** [comment]
@mrodriguez3313  I started a new PR here. I updated the format of the [video title to match the format in the Style Guide](https://github.com/protocol/launchpad/blob/v4-ipld-and-ipfs/STYLE-GUIDE.md#titles), added in the first summary paragraph to this branch: [https://github.com/protocol/launchpad/tree/v4-ipld-and-ipfs](https://github.com/protocol/launchpad/tree/v4-ipld-and-ipfs)

You can add the next 2 paragraphs to this, and once I have your version of the edited video uploaded to YouTube, we can put that in this as well, then make a PR & have Enol review!

**Comment by mrodriguez3313** [comment]
Latest PR is here #171 . It has the link to the video and the summary in the commit :thumbsup:

**Comment by mrodriguez3313** [comment]
Closing issue because PR was successfully merged!
