### ISSUE TITLE
Section about the IPFS API and hands-on exercise

### ISSUE THREAD

**Issue by enoldev** [protocol/launchpad#146]
### Purpose
Part of improving the curriculum of _deep_ students is providing hands-on exercises.

### Proposed Solution
- Introduce the IPFS API and the Go/JS development ecosystem
- Create a hands-on exercise where they get to implement a simple application by using the Go client. Go is the primary implementation language of IPFS.

**Where Can we find out more about this topic?**
- https://docs.ipfs.io/reference/
- https://github.com/ipfs/go-ipfs-api

## Acceptance Criteria
- A section describing the IPFS API and the Go/JS development ecosystem
- A hands-on exercise that student can complete by using the IPFS Go client

**Comment by walkerlj0** [comment]
Done: http://localhost:1313/curriculum/ipfs/ipfs-api/
