### ISSUE TITLE
Dated info, link update needed

### ISSUE THREAD

**Issue by asilinphoto** [protocol/launchpad#148]
**What section and page of the Curriculum is this on**
_ex:_  _IPFS: The IPFS Gateways_

**Describe the bug**
1. Under "[Launchpad Principles](https://protocol-labs.gitbook.io/launchpad-curriculum/about-launchpad)", "Improve as we go" #pl-bootcamp-v1 is referenced but seems to be archived, or renamed to #pl-launchpad. Is this channel by invitation only, or has this information changed?
2. Under "[Launchpad Principles](https://protocol-labs.gitbook.io/launchpad-curriculum/about-launchpad)", "Async first", the link [here](https://protocol-labs.gitbook.io/launchpad-curriculum/about-launchpad) links to the page its currently on. Since there are a few articles on async work, which should this be updated to?

_If it is additional content or a large change, create a curriculum feature request_

**If applicable, add screenshots to help explain your problem**
![Screen Shot 2022-06-27 at 9 58 48 AM](https://user-images.githubusercontent.com/99894913/175959352-6bedb68c-5ee8-48cb-8741-87d41dc97a77.png)

**Comment by walkerlj0** [comment]
Thanks @asilinphoto those are fixed, removed them both! https://protocol-labs.gitbook.io/launchpad-curriculum/about-launchpad
