### ISSUE TITLE
Create Video for IPFS API Tutorial

### ISSUE THREAD

**Issue by walkerlj0** [protocol/launchpad#151]
## Problem Description
Video of tutorial here

### Purpose
_Describe what need this projectr is filling, or what problem is sovling, and who the intended audience or end user is_

### Proposed Solution
What features, user stories, or product/ content you would like as an output

**Where Can we find out more about this topic?**

**Additional context**

## Milestones
**1) Milstone Name** Text

**2) Milstone Name** Text

## Acceptance Criteria
_Describe the out put and criteria for this output for considering this task completed_

**Comment by enolal826** [comment]
The video is here: https://drive.google.com/file/d/1oMC3weZ0eKD-RV-zPJt1nB-7YeniYe8E/view?usp=sharing
The transcription: https://docs.google.com/document/d/1-oFHJyz0Q_KC6RZcWVAukkFZrMXnWnjPOWdH0b2xsbc/edit?usp=sharing

@walkerlj0

**Comment by walkerlj0** [comment]
Started putting it on the page/ shoring up written with video here: https://github.com/protocol/launchpad/pull/257

Added script to notion: https://www.notion.so/protocollabs/Script-IPFS-API-Tutorial-b3c5b939a57b4b2d8349d64f6909a6ac

**Comment by walkerlj0** [comment]
Only a few small changes
There's one additional thing I have asked to show in the video, and I think this need title videos for each subsection/ function.

I have added yellow highlighted feedback in the script: https://www.notion.so/protocollabs/Script-IPFS-API-Tutorial-b3c5b939a57b4b2d8349d64f6909a6ac

I also added a few updates with more clear directions, and (mathcing) titles for each section in the written tutorial: https://github.com/protocol/launchpad/pull/257

**Comment by enolal826** [comment]
I've created this new version:
https://drive.google.com/file/d/1xlxfAFa1LaTUB35ykM3fJQ-AN516Wej7/view?usp=sharing

**Comment by walkerlj0** [comment]
@enolal826 looks ready to ship/ merge to me! Added the video in & a more descriptive subtitle
