### ISSUE TITLE
Broken URL in IPFS Gateway section

### ISSUE THREAD

**Issue by mrodriguez3313** [protocol/launchpad#164]
**What section and page of the Curriculum is this on**
IPFS: The IPFS Gateways

**Describe the bug**
URL on line 14 under [subdomain-gateways](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/ipfs/ipfs-gateways#subdomain-gateway) is invalid. Current url looks like: 
../concepts/content-addressing.md#identifier-formats -> https://github.com/protocol/launchpad/blob/gitbook/docs/concepts/content-addressing.md#identifier-formats

I don't know if the ipfs docs url for [content addressing](https://docs.ipfs.io/concepts/content-addressing/#identifier-formats) was meant to be inserted or was the launchpad url meant to be there for [content addressing](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/ipld/content-addressing-and-cids#content-identifiers-cids). I personally like the first link and think that one should be in place there.

Another broken URL is on line 126 under [How to address ipfs on the web](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/ipfs/ipfs-gateways#how-to-address-ipfs-on-the-web). Not sure what this one is supposed to link to.

**Comment by walkerlj0** [comment]
@mrodriguez3313 feel free to close or improve

**Comment by mrodriguez3313** [comment]
Resolved in PR #187
