### ISSUE TITLE
Dead link to libp2p examples

### ISSUE THREAD

**Issue by CluEleSsUK** [protocol/launchpad#191]
**What section and page of the Curriculum is this on**
libp2p: libp2p resources

**Describe the bug**
The link to examples within the following text is broken:
`
If you want to get a feel for what's possible with libp2p, or just want to see some idiomatic usage, check out the [examples](https://github.com/protocol/launchpad/blob/main/examples/README.md). Each libp2p implementation maintains a set of working example projects that can illustrate key concepts and use cases.
`
I poked around to try and find the relevant link to raise a PR, but couldn't find it - sorry!

**Comment by walkerlj0** [comment]
@enolal826 can you fix this in the migrated version?
