### ISSUE TITLE
github onboarding

### ISSUE THREAD

**Issue by mrodriguez3313** [protocol/launchpad#211]
## Problem Description
Add a shallow and deep dive on GH for "best practices, tips, & tricks"

## Purpose
_Describe what need this project is filling, or what problem it's solving, and who the intended audience or end user is_

The curriculum goes over [best practices for contributing to open source projects](https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/protocol-labs-network/os-contributing#how-to-contribute), but it does not go over **_how_** github is used for governance and discussion (ie. [Filecoin Improvement Proposals (FIPs)](https://github.com/filecoin-project/FIPs)), ticketing and requests (ie. [design shop](https://github.com/protocol/design-shop/issues)) in the org as a whole. This, by extension, means we include markdown tips and tricks to teach common and helpful uses in GH comments and PRs.

_**This will help prep new employees (in or out of PL/PLN) for their new positions a bit more.**_

## Proposed Solution

Additional section within either Additional Resources or OS-Contributing on how to we use GH in the org && GH tips and tricks.

**Where Can we find out more about this topic?**
* https://youtu.be/yzeVMecydCE?t=1512
* https://protocol-labs.gitbook.io/launchpad-curriculum/launchpad-learning-resources/protocol-labs-network/os-contributing
* add more here...

**Additional context**
Feature requests are not limited to those listed above. Any additions/suggestions welcomed!

## Milestones
**1) Usage & usage**
Find out more of **_how_** GH is used around the org and look into other potential GH markdown features to outline.

**2) Elevator pitches**
Create short form descriptions of how each are used. Potentially bullet point style (ex: Docs - Async and public collaborative effort to formulate the subjectively best way to educate the reader of our software.)

**3) Collaborate**
Ditto my example above. Create PR to get reviews from invested parties.

## Acceptance Criteria
Roughly half a page of content outlining and highlighting GH usage around the org and material that better prepares members on how to use GH.

P.S. Thank you to @dmc314 for the content suggestion

**Comment by walkerlj0** [comment]
@kt-wawro  add your Github resources here

**Comment by walkerlj0** [comment]
MVP & updated versions were created!
