### ISSUE TITLE
Create Chunking & How to build a DAG content in IPLD

### ISSUE THREAD

**Issue by walkerlj0** [protocol/launchpad#219]
## Problem Description
Create two new sections on chunking and building an ipld merkle dag.

### Purpose
There currently is nowhere in the curriculum that explains how to do this in writing. ["How IPFS deals with files (v1)" goes over this](https://youtu.be/Y_-TWTmF_1I?t=1153) with a good Q&A section at the end. This is needed because it is an important concept for understanding how IPFS works under-the-hood and the intersection between IPLD & IPFS.

### Proposed Solution
The goal will be to add a section that's about a page long, that will contain a cut-down edited version of "How IPFS deals with files (V1)" and an overview of that video section, underneath. Similar to: https://curriculum.pl-launchpad.io/curriculum/ipfs/how-ipfs-works/. 

Work with @warpfork & or @rvagg to create an up-to-date version of the written part of the curriculum. 
**Where can we find out more about this topic?** 
* **Find more resources on chunking!!**

**Additional context**

## Milestones
**1) Video editting**
Cut down video to only be about 10 minutes long.

**2) Write up**
Write summary of video

**3) Reviews**
Work with experts to check correctness and add additional details to curriculum.

## Acceptance Criteria
Acceptable result includes an edited video and description of that video. Consideration should be taken on if this should be its own lesson or integrated within an existing one?

**Comment by walkerlj0** [comment]
@mrodriguez3313 Add it to spreadsheet, then @ me here, I will publish video & approve PR

**Comment by walkerlj0** [comment]
@marco published here: https://youtu.be/z9GmPIfqUbE

**Comment by mrodriguez3313** [comment]
PR is here https://github.com/protocol/launchpad/pull/238

**Comment by walkerlj0** [comment]
Approved if you make the changes: https://github.com/protocol/launchpad/pull/238#pullrequestreview-1109819407
