### ISSUE TITLE
Platform Feature – Link from old gitbook -> new

### ISSUE THREAD

**Issue by walkerlj0** [protocol/launchpad#220]
**User Story**
As a former Launchpad resident, or user who has already referenced Launchpad materials I would like to be able to see where newest, updated content is so that I can access the most up to date information

**Describe the solution you'd like**
For now, have a bold notice or banner directing to the new curriculum page

**Comment by mrodriguez3313** [comment]
I created an alert box to each module page though Gitbook UI. To merge this to our gitbook branch, I need a reviewer in that platform. @walkerlj0 @enolal826 

![Alert_box](https://user-images.githubusercontent.com/22666025/187093416-37b559b6-ddbd-4bf4-aa6c-2be569ff1f36.png)

**Comment by mrodriguez3313** [comment]
Done: [https://protocol-labs.gitbook.io/launchpad-curriculum/](https://protocol-labs.gitbook.io/launchpad-curriculum/)
