### ISSUE TITLE
Learning Platform Bug - No Mobile Menu

### ISSUE THREAD

**Issue by walkerlj0** [protocol/launchpad#233]
** Describe the use case**
Go from the landing page/ other curriculum pages into a different section (e.g. pre-requisites, curriculum, or Resources) on mobiile (Pixel 6 Android Latest) 

** Describe the problem**
There were no menu items to use to navigate or even determine what other pages were on the site on mobile
![Screenshot_20220826-130044](https://user-images.githubusercontent.com/66978602/186965596-4888ea07-60e8-418e-9c53-f02a246e9908.png)

**Proposed Solution**
Add menu Items for, at a minimum, Pre-Reqs, Curriculum, and Resources-- Ideally one level down with areas such as IPFS, IPLD, etc

How can this Problem be solved?

**Comment by enolal826** [comment]
Fixed here https://github.com/protocol/launchpad/pull/235
