### ISSUE TITLE
[Don't Fix - Will fix in LP on Wednesday as an example] Link to Ceramic on Dev-Tools Intro to Toolkits

### ISSUE THREAD

**Issue by daveo101** [protocol/launchpad#236]
**What section and page of the Curriculum is this on**
Dev-Tools: Introduction to Toolkits

**Describe the bug**
Ceramic link doesn't work

**Comment by jbrawny** [comment]
What section and page of the Curriculum is this on
Dev-Tools: Introduction to Toolkits

Describe the bug
Pinata link doesn't work

**Comment by aysmed** [comment]
web3.storage link not working either

**Comment by celine3650** [comment]
[Piñata] link is not working

**Comment by maddhuynh** [comment]
Textile https://curriculum.pl-launchpad.io/dev-tools/toolkits/introduction/textile.md
Ceramic https://curriculum.pl-launchpad.io/dev-tools/toolkits/introduction/ceramic.md

dont work

**Comment by caitlin-moore** [comment]
ceramic link is not working

**Comment by Qingwarthen** [comment]
Fleek is not working either. 
https://curriculum.pl-launchpad.io/dev-tools/toolkits/introduction/fleek-space-daemon.md

**Comment by Kdonovan1231** [comment]
pinanta does not work: https://curriculum.pl-launchpad.io/dev-tools/toolkits/introduction/pinata.md

**Comment by kaylakroot** [comment]
Textile is broken, and Fission goes to an article as opposed to their direct website

**Comment by maddhuynh** [comment]
Fleek https://curriculum.pl-launchpad.io/dev-tools/toolkits/introduction/fleek-space-daemon.md 
Pinata https://curriculum.pl-launchpad.io/dev-tools/toolkits/introduction/pinata.md
don't work either

**Comment by RitaBWathigo** [comment]
Textile link: https://curriculum.pl-launchpad.io/dev-tools/toolkits/introduction/textile.md does not work
Cermaic link: https://curriculum.pl-launchpad.io/dev-tools/toolkits/introduction/ceramic.md does not work
