### ISSUE TITLE
Simple link fix

### ISSUE THREAD

**Issue by RyanCoordinator** [protocol/launchpad#254]
**What section and page of the Curriculum is this on**
https://curriculum.pl-launchpad.io/curriculum/pln/os-stewardship/

**Describe the bug**
The link at the bottom of the page to the next page should point to https://curriculum.pl-launchpad.io/curriculum/pln/os-contributing/ (the next page in sequence), but instead points to https://curriculum.pl-launchpad.io/curriculum/ipfs/objectives/ skipping a page.

Simple fix, thought I should be a good citizen and create an issue :)

**Comment by mrodriguez3313** [comment]
Ahh good catch I will fix this. Thank you!

**Comment by mrodriguez3313** [comment]
@walkerlj0 @enoldev 
There is a bigger problem here that we didn't realize. When we add a new page to the curriculum we add a [weight to it](https://github.com/protocol/launchpad/pull/267/commits/6f8aefe993817ce37fc4d987677897627b0ac503) But if there are any pages that have equal weights, the Hugo will populate the "Next" button link at the bottom of the page with the one furthest down in the heirarchy. 

This fix will require me to edit every single page potentially to make sure that we don't run into this problem later on. 

@enoldev  Or do you think there might be a way to programatically assign weights?

**Comment by mrodriguez3313** [comment]
Other example of this happening is at the bottom of: https://curriculum.pl-launchpad.io/curriculum/ipfs/ipfs-gateways/ (skips two sections)

**Comment by walkerlj0** [comment]
Hey @mrodriguez3313 to try and head off this program, we incremented by at least 10 for each page in anticipation of the need to add pages in between. For example, IPFS intro has a weight of 70, and the next page the CLI setup has a weight of 80-- so if you need to add a page in between you just give it a weight of 75.

Make sure you are noting the weights before and after when adding pages, and putting them in between like the example above.

**Comment by mrodriguez3313** [comment]
My b 😅
