### ISSUE TITLE
libp2p tutorial - Handlers

### ISSUE THREAD

**Issue by enoldev** [protocol/launchpad#256]
A tutorial that teaches how to use handlers to exchange data

**Comment by walkerlj0** [comment]
@enoldev can I get links to all relevant material here? E.g. video URL, PRs, and scripts?

**Comment by enoldev** [comment]
@walkerlj0 Video ready.

Video: https://drive.google.com/file/d/1h3Jox46aaabFLlGFSgLS-gb3XiAgw6FO/view?usp=sharing
Content PR: https://github.com/protocol/launchpad/pull/255
Scripts PR: https://github.com/protocol/launchpad-tutorials/pull/4

**Comment by enoldev** [comment]
@walkerlj0 After the feedback, here's the new version https://drive.google.com/file/d/1DZFzL6xSY--trZWZBZDlsX9lEDvnPzDr/view?usp=sharing

I think we can push it to YouTube

**Comment by walkerlj0** [comment]
Let me know when It's updated in the YouTube spreadsheet & ready to go
- Lindsay Walker
https://ovou.me/lindz

**Comment by enol** [comment]
You are talking to the wrong Enol. I’m not a member of this project
