### ISSUE TITLE
Migrate PL website & curriculum Site to team Fleek

### ISSUE THREAD

**Issue by walkerlj0** [protocol/launchpad#293]
** Describe the use case**
Migrate both the [Launchpad website](https://www.notion.so/protocollabs/Fleek-account-migration-guide-c091cd0c0d6d426092f46474f40bcf0e) and [Curriculum site](https://github.com/protocol/launchpad) to a shared team Fleek account

[Fleek Migration Guide](https://www.notion.so/protocollabs/Fleek-account-migration-guide-c091cd0c0d6d426092f46474f40bcf0e)

** Describe the problem**
Context: 
**Jeff Everett**

Hi Lindsay-- as we've continued to add stuff to pathfinder account, there is a pretty strong preference to not share that account.
Can I help get whatever site(s) Marco needs to work with moved to your own fleek account instead?
I've gone through this with another team and had some initial feedback-- the fact fleek is able to basically just update an existing site to be owned by another account means we don't have to do any changes in git or DNS, so it's pretty straightforward.: https://www.notion.so/protocollabs/Fleek-account-migration-guide-c091cd0c0d6d426092f46474f40bcf0e
If there's an urgency around fixing something, we can potentially add Marco to pathfinder, but we're really trying to avoid creating the same situation that made us need to move away from the old shared protocol team account to begin with.

**Proposed Solution**
How can this Problem be solved?

**Comment by walkerlj0** [comment]
@walkerlj0 needs to talk to Molly/ Walker & Johnny about this need, and see if 
A) We migrate away from Pathfinder
B) Talk to Johnny about how we set up docs

**Comment by walkerford** [comment]
LP now has a Fleek account that hosts both repos.
