### ISSUE TITLE
Launchpad Network Partners Section

### ISSUE THREAD

**Issue by kt-wawro** [protocol/launchpad#326]
As we shift to serve our network partners better adding in more content for our network partners both in messaging about the program on the launchpad website and in our content. 

### Purpose
The end user would be for founders and people who work at our network partners. 

### Proposed Solution

**Network Partner Messaging Rebrand:**
- Testimonials focused on network partners
- Highlight the people that will do the shallow and deep dives
- Stronger messaging about tracks including level-up with Launchpad
- Stronger messaging about what network partners will learn
- Messaging about hiring through Launchpad

**Content for Network Partners:** 
- More technical modules on tokennomics, rust, FVM etc. 
-More non-technical modules for marketing in web3, the business of being a storage provider etc. 
-Specific network partner section fo the Launchpad curriculum
-Strech goal: Different pages highlighting the work that our network partners are doing

**Comment by walkerlj0** [comment]
Closing as this is a separate issue for the website repo, not Launchpad page. WIP, please re-open the issue here: https://github.com/pathfindertools/pl-launchpad
