### ISSUE TITLE
Confusing information in CONTRIBUTING.md

### ISSUE THREAD

**Issue by bajtos** [protocol/launchpad#343]
**Describe the use case**

When submitting my first PR, GitHub helpfully pointed me to [contributing guidelines](https://github.com/protocol/launchpad/blob/0a98237e76c3ae23163db5a7109c76a52bacc713/CONTRIBUTING.md)

**Describe the problem**

The guidelines left me confused.

The first sentence asks me to target the branch `gitbook`. I can see the branch exists, but it haven't been updated for many months. The `main` branch seems to be the one receiving pull requests.

Then there is the "Steps" section which instructs me to ask for admin access. That's even more confusing. I don't want the responsibility of having admin permissions, when all I want is to make a one-time contribution.

There is also a mention of `gh-pages` branch which does not seem to exist at all.

**Proposed Solution**

Let's clarify the contribution process. Make it clear which instructions apply to occasional contributors and which are for project maintainers.

**Comment by walkerlj0** [comment]
Thanks for the feedback, that was deprecated, updated with this PR @bajtos https://github.com/protocol/launchpad/pull/349

**Comment by walkerlj0** [comment]
Thanks!

**Comment by bajtos** [comment]
Perfect, thank you @walkerlj0! 🙏🏻
