### ISSUE TITLE
Use of Ampersand vs And

### ISSUE THREAD

**Issue by jmslnch** [protocol/launchpad#424]
**What section and page of the Curriculum is this on**
Protocol Labs Network - Learning Objectives

**Describe the bug**
At times the word 'and' is used, at other times an '&' is used. This is grammatically confusing.

**If applicable, add screenshots to help explain your problem**
<img width="804" alt="Screen Shot 2022-12-08 at 4 16 08 PM" src="https://user-images.githubusercontent.com/114518658/206578822-a4e7bd48-0319-45ed-97e4-b344666fec80.png">

**Additional context**
The discrepancy appears on the first page of the curriculum and then occasionally throughout.

**Comment by walkerlj0** [comment]
We will be working on a Style Guide and come up with a consistent way, good catch! Thanks!
