### ISSUE TITLE
Rename "Apply" button to "Jobs Board" on homepage

### ISSUE THREAD

**Issue by walkerford** [protocol/launchpad#447]
**Describe the use case**
Anyone coming to the Launchpad website wanting to register.

**Describe the problem**
There are two buttons right next to each other with names that sound the same.

**Proposed Solution**
- Change the "Apply" button to something like "Jobs Board".
- Move the "Register Here" button to be the first button.  This is the most important action on the page.

**Comment by seunbayo** [comment]
can this be assigned to me? @walkerford @walkerlj0
