### ISSUE TITLE
twitter-banner-1500x500.png missing

### ISSUE THREAD

**Issue by rvagg** [protocol/launchpad#45]
.gitbook/assets/twitter-banner-1500x500.png is referenced in a bunch of places, maybe this is a standard file but we should put one in here or remove those links

**Comment by walkerlj0** [comment]
Ah- this was just a placeholder image that I used as a template-- if you notice it's only in the two sections that don't have content yet (docs/built-on-ipgs and docs/protocol-labs-toolkits)
