### ISSUE TITLE
Put all Learning Goals in the Same page

### ISSUE THREAD

**Issue by walkerlj0** [protocol/launchpad#455]
## Problem Description
There are two Learning Goals pages. Make sure that the [ONE source of truth is update](https://www.notion.so/pl-strflt/8e6c3e8aa7a446ecb4a2f6cd55462218?v=43c411da4dbf45838a18716547c50929)
- Move all the information over from the [Archived (non-used) version](https://www.notion.so/pl-strflt/08110afed0214f4b8fb85595c5013549?v=d46dfa04c4bf4d51aad7e14b7622cfe5)

Make sure each matches up with goals.json and the Miro Board:
https://miro.com/app/board/uXjVOB6tchQ=/

**Where Can we find out more about this topic?**

**Additional context**

## Milestones (Optional)
**1) Milstone Name** Text

**2) Milstone Name** Text

## Acceptance Criteria
_Describe the out put and criteria for this output for considering this task completed_

**Comment by mrodriguez3313** [comment]
Done! 😄

**Comment by walkerlj0** [comment]
@marco the IPFS and IPLD look great, however it looks like libp2p and PLN still need updating!

Take a look at this, and also make sure you cross reference everthing with the goals.json! 

![Image](https://user-images.githubusercontent.com/66978602/211911276-11761c3f-46e5-4828-a5c9-701d900aaf06.png)
![Image](https://user-images.githubusercontent.com/66978602/211911277-5a7f6d0a-e658-4b9d-9b95-2527421f2cb9.png)

**Comment by walkerlj0** [comment]
Note-- Updated & Done! https://www.notion.so/pl-strflt/8e6c3e8aa7a446ecb4a2f6cd55462218?v=43c411da4dbf45838a18716547c50929
