### ISSUE TITLE
libp2p missing links

### ISSUE THREAD

**Issue by rvagg** [protocol/launchpad#46]
libp2p/core-concepts.md and libp2p/libp2p-resources contain links to `https://github.com/protocol/launchpad/blob/main/` (old) that don't exist on the new - have they bee renamed? they should be relative links, we need to remove all content links to `https://github.com/protocol/launchpad/...`, I think they were GitBook dealing with bad links.

It'd be worth reviewing all links in the libp2p docs, they've become a little whacky after their round-trip through gitbook.

**Comment by walkerlj0** [comment]
This is also just part of a template page-- placeholder link. Can ignore, will be done once the two unfinished sections are done
