### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by ElPaisano** [protocol/launchpad#486]
**What section and page of the Curriculum is this on**
https://github.com/protocol/launchpad#contributing-to-the-launchpad-curriculum

**Describe the bug**
The link in the second bullet point in https://github.com/protocol/launchpad#contributing-to-the-launchpad-curriculum is 404ing. The link is https://github.com/protocol/launchpad/blob/templates/STYLE-GUIDE.md. 

Searching the repo, I see https://github.com/protocol/launchpad/blob/main/STYLE-GUIDE.md but do not see a https://github.com/protocol/launchpad/blob/templates/STYLE-GUIDE.md.

**Additional context**
Not sure where this should link to instead, otherwise I'd just create a PR to fix it, so I figured I would bring it to the teams attention.

**Comment by walkerlj0** [comment]
Thank you for your flagging this @ElPaisano ! We have fixed that link now with this PR: https://github.com/protocol/launchpad/commit/0c78b823d6b4eee76bf3952f14ca4e72216ac87e
