### ISSUE TITLE
Add thirdweb to LaunchPad DevTools Curriculum page

### ISSUE THREAD

**Issue by mikedjshin** [protocol/launchpad#515]
thirdweb is a complete web3 development framework that provides everything you need to build, manage, and deploy smart contracts. We offer SDKs in common languages, UI components, storage, RPC nodes, on chain data, and more tools to make it easier to build in web3.

Purpose
Provide Launchpad a quick and easy way to deploy smart contracts and more.

Proposed Solution
List thirdweb in "Dev Tools" section here - https://curriculum.pl-launchpad.io/curriculum/dev-tools/objectives/

Where can we find out more about this topic?
Katie W

**Comment by kt-wawro** [comment]
Added here [PR](https://github.com/protocol/launchpad/pull/517#issue-1618120538)

**Comment by walkerford** [comment]
Closed in PR #517
