### ISSUE TITLE
 Contributing to Launchpad Curriculum section in the README Link

### ISSUE THREAD

**Issue by kdkarl** [protocol/launchpad#89]
** Describe the use case**
-
** Describe the problem**
The link in https://protocol-labs.gitbook.io/launchpad-curriculum/about-launchpad page, [Contributing to Launchpad Curriculum section in the README](https://github.com/protocol/launchpad/blob/gitbook/docs/README.md) has a 404 error

**Proposed Solution**
fix the link

**Comment by DeveloperAlly** [comment]
Link probably this one: https://github.com/protocol/launchpad/blob/gitbook/README.md

No longer nested undeers docs:
https://github.com/protocol/launchpad/blob/gitbook/docs/README.md

**Comment by walkerlj0** [comment]
Thanks both! This has been resolved @kdkarl
